# Generated by Django 2.2.2 on 2019-08-18 11:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_auto_20190818_1700'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Wallet',
            new_name='Profile',
        ),
    ]
