# Generated by Django 2.2.2 on 2019-08-20 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20190818_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='IdCardNo',
            field=models.CharField(default=0, max_length=11),
        ),
    ]
